using System;
using System.Globalization;

using System.Runtime.CompilerServices;
namespace CleanFoundation
{
    [Serializable]
    public partial struct Vector3Int : IEquatable<Vector3Int>, IFormattable
    {
        private int m_X,m_Y,m_Z;
        public int x{[MethodImpl(MethodImplOptions.AggressiveInlining)] readonly get=>m_X;[MethodImpl(MethodImplOptions.AggressiveInlining)] set=>m_X=value;} public int y{[MethodImpl(MethodImplOptions.AggressiveInlining)] readonly get=>m_Y;[MethodImpl(MethodImplOptions.AggressiveInlining)] set=>m_Y=value;} public int z{[MethodImpl(MethodImplOptions.AggressiveInlining)] readonly get=>m_Z;[MethodImpl(MethodImplOptions.AggressiveInlining)] set=>m_Z=value;}
        public int this[int index]{[MethodImpl(MethodImplOptions.AggressiveInlining)] readonly get{switch(index){case 0:return m_X;case 1:return m_Y;case 2:return m_Z;default:throw new IndexOutOfRangeException($"Invalid Vector3Int index addressed: {index}!");}}[MethodImpl(MethodImplOptions.AggressiveInlining)] set{switch(index){case 0:m_X=value;break;case 1:m_Y=value;break;case 2:m_Z=value;break;default:throw new IndexOutOfRangeException($"Invalid Vector3Int index addressed: {index}!");}}}
        public readonly float magnitude { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => Mathf.Sqrt((float)(m_X*m_X+m_Y*m_Y+m_Z*m_Z)); } public readonly int sqrMagnitude { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => m_X*m_X+m_Y*m_Y+m_Z*m_Z; }
        public static Vector3Int zero { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => new Vector3Int(0,0,0); } public static Vector3Int one { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => new Vector3Int(1,1,1); } public static Vector3Int up { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => new Vector3Int(0,1,0); } public static Vector3Int down { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => new Vector3Int(0,-1,0); } public static Vector3Int left { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => new Vector3Int(-1,0,0); } public static Vector3Int right { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => new Vector3Int(1,0,0); } public static Vector3Int forward { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => new Vector3Int(0,0,1); } public static Vector3Int back { [MethodImpl(MethodImplOptions.AggressiveInlining)] get => new Vector3Int(0,0,-1); }
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public Vector3Int(int x,int y){m_X=x;m_Y=y;m_Z=0;} [MethodImpl(MethodImplOptions.AggressiveInlining)] public Vector3Int(int x,int y,int z){m_X=x;m_Y=y;m_Z=z;} [MethodImpl(MethodImplOptions.AggressiveInlining)] public void Set(int x,int y,int z){m_X=x;m_Y=y;m_Z=z;}
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public static float Distance(Vector3Int a,Vector3Int b)=>Distance(in a,in b); [MethodImpl(MethodImplOptions.AggressiveInlining)] public static float Distance(in Vector3Int a,in Vector3Int b){float x=a.m_X-b.m_X,y=a.m_Y-b.m_Y,z=a.m_Z-b.m_Z;return (float)Math.Sqrt((double)x*x+(double)y*y+(double)z*z);}
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public static Vector3Int Min(Vector3Int a,Vector3Int b)=>new Vector3Int(Mathf.Min(a.m_X,b.m_X),Mathf.Min(a.m_Y,b.m_Y),Mathf.Min(a.m_Z,b.m_Z)); [MethodImpl(MethodImplOptions.AggressiveInlining)] public static Vector3Int Min(in Vector3Int a,in Vector3Int b)=>Min(a,b);
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public static Vector3Int Max(Vector3Int a,Vector3Int b)=>new Vector3Int(Mathf.Max(a.m_X,b.m_X),Mathf.Max(a.m_Y,b.m_Y),Mathf.Max(a.m_Z,b.m_Z)); [MethodImpl(MethodImplOptions.AggressiveInlining)] public static Vector3Int Max(in Vector3Int a,in Vector3Int b)=>Max(a,b);
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public static Vector3Int Scale(Vector3Int a,Vector3Int b)=>new Vector3Int(a.m_X*b.m_X,a.m_Y*b.m_Y,a.m_Z*b.m_Z); [MethodImpl(MethodImplOptions.AggressiveInlining)] public static Vector3Int Scale(in Vector3Int a,in Vector3Int b)=>Scale(a,b);
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public void Scale(Vector3Int s){m_X*=s.m_X;m_Y*=s.m_Y;m_Z*=s.m_Z;} [MethodImpl(MethodImplOptions.AggressiveInlining)] public void Scale(in Vector3Int s){m_X*=s.m_X;m_Y*=s.m_Y;m_Z*=s.m_Z;}
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public void Clamp(Vector3Int min,Vector3Int max){m_X=Mathf.Clamp(m_X,min.m_X,max.m_X);m_Y=Mathf.Clamp(m_Y,min.m_Y,max.m_Y);m_Z=Mathf.Clamp(m_Z,min.m_Z,max.m_Z);} [MethodImpl(MethodImplOptions.AggressiveInlining)] public void Clamp(in Vector3Int min,in Vector3Int max){Clamp(min,max);}
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public static Vector3Int FloorToInt(Vector3 v)=>new Vector3Int(Mathf.FloorToInt(v.x),Mathf.FloorToInt(v.y),Mathf.FloorToInt(v.z)); [MethodImpl(MethodImplOptions.AggressiveInlining)] public static Vector3Int FloorToInt(in Vector3 v)=>FloorToInt(v);
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public static Vector3Int CeilToInt(Vector3 v)=>new Vector3Int(Mathf.CeilToInt(v.x),Mathf.CeilToInt(v.y),Mathf.CeilToInt(v.z)); [MethodImpl(MethodImplOptions.AggressiveInlining)] public static Vector3Int CeilToInt(in Vector3 v)=>CeilToInt(v);
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public static Vector3Int RoundToInt(Vector3 v)=>new Vector3Int(Mathf.RoundToInt(v.x),Mathf.RoundToInt(v.y),Mathf.RoundToInt(v.z)); [MethodImpl(MethodImplOptions.AggressiveInlining)] public static Vector3Int RoundToInt(in Vector3 v)=>RoundToInt(v);
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public static Vector3Int operator +(Vector3Int a,Vector3Int b)=>new Vector3Int(a.m_X+b.m_X,a.m_Y+b.m_Y,a.m_Z+b.m_Z); [MethodImpl(MethodImplOptions.AggressiveInlining)] public static Vector3Int operator -(Vector3Int a,Vector3Int b)=>new Vector3Int(a.m_X-b.m_X,a.m_Y-b.m_Y,a.m_Z-b.m_Z); [MethodImpl(MethodImplOptions.AggressiveInlining)] public static Vector3Int operator *(Vector3Int a,Vector3Int b)=>new Vector3Int(a.m_X*b.m_X,a.m_Y*b.m_Y,a.m_Z*b.m_Z); [MethodImpl(MethodImplOptions.AggressiveInlining)] public static Vector3Int operator -(Vector3Int a)=>new Vector3Int(-a.m_X,-a.m_Y,-a.m_Z); [MethodImpl(MethodImplOptions.AggressiveInlining)] public static Vector3Int operator *(Vector3Int a,int b)=>new Vector3Int(a.m_X*b,a.m_Y*b,a.m_Z*b); [MethodImpl(MethodImplOptions.AggressiveInlining)] public static Vector3Int operator *(int a,Vector3Int b)=>b*a; [MethodImpl(MethodImplOptions.AggressiveInlining)] public static Vector3Int operator /(Vector3Int a,int b)=>new Vector3Int(a.m_X/b,a.m_Y/b,a.m_Z/b);
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public static bool operator ==(Vector3Int a,Vector3Int b)=>a.m_X==b.m_X&&a.m_Y==b.m_Y&&a.m_Z==b.m_Z; [MethodImpl(MethodImplOptions.AggressiveInlining)] public static bool operator !=(Vector3Int a,Vector3Int b)=>!(a==b); [MethodImpl(MethodImplOptions.AggressiveInlining)] public override readonly bool Equals(object obj)=>obj is Vector3Int o&&Equals(o); [MethodImpl(MethodImplOptions.AggressiveInlining)] public readonly bool Equals(Vector3Int o)=>this==o; [MethodImpl(MethodImplOptions.AggressiveInlining)] public readonly bool Equals(in Vector3Int o)=>this==o; [MethodImpl(MethodImplOptions.AggressiveInlining)] public override readonly int GetHashCode(){int hy=m_Y.GetHashCode(),hz=m_Z.GetHashCode();return m_X.GetHashCode()^hy<<4^hy>>28^hz>>4^hz<<28;}
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public override readonly string ToString()=>ToString(null,null); [MethodImpl(MethodImplOptions.AggressiveInlining)] public readonly string ToString(string format)=>ToString(format,null); [MethodImpl(MethodImplOptions.AggressiveInlining)] public readonly string ToString(string format,IFormatProvider provider){if(provider==null)provider=CultureInfo.InvariantCulture.NumberFormat;return $"({m_X.ToString(format,provider)}, {m_Y.ToString(format,provider)}, {m_Z.ToString(format,provider)})";}
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public static implicit operator Vector3(Vector3Int v)=>new Vector3(v.m_X,v.m_Y,v.m_Z); [MethodImpl(MethodImplOptions.AggressiveInlining)] public static explicit operator Vector2Int(Vector3Int v)=>new Vector2Int(v.m_X,v.m_Y); public static explicit operator Vector3Int(Vector2Int v)=>new Vector3Int(v.x,v.y,0);
#if UNITY_5_3_OR_NEWER
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public static implicit operator UnityEngine.Vector3Int(Vector3Int v)=>new UnityEngine.Vector3Int(v.m_X,v.m_Y,v.m_Z);
        [MethodImpl(MethodImplOptions.AggressiveInlining)] public static implicit operator Vector3Int(UnityEngine.Vector3Int v)=>new Vector3Int(v.x,v.y,v.z);
#endif
    }
}
